#!/bin/bash
asd=$"(defsystem \"$1\"
	:author \"Leonardo Zamboni <leonardonunes169@gmail.com>\"
  	:maintainer \"Leonardo Zamboni <leonardonunes169@gmail.com>\"  
	:license \"LLGPL\"
  	:version \"0.1\"
  	:homepage \"https://github.com/leozamboni/$1\"
  	:bug-tracker \"https://github.com/leozamboni/$1/issues\"
  	:source-control (:git \"git@github.com:leozamboni/$1.git\")
  	:description \"\"
  	:depends-on ()
  		:components ((:module \"src\"
                	:serial t
	                :components
        	        ((:file \"\")))))
  	:long-description
  	#.(uiop:read-file-string
     	(uiop:subpathname *load-pathname* \"README\"))"
mkdir $1 && cd $1 && mkdir src && printf "$asd" > $1.asd 
