#!/bin/bash

if [[ "$1" == "fix" ]] 
then
	message=":wrench: fix: $2"
elif [[ "$1" == "refact" ]]
then
	message=":building_construction: refact: $2"
elif [[ "$1" == "feat" ]]
then
	message=":sparkles: feat: $2"
fi

echo $message
git commit -m "$message"
