#!/bin/bash

echo ";; This software is Copyright (c) Leonardo Z. Nunes, $(date +%Y).
;; grants you the rights to distribute
;; and use this software as governed by the terms
;; of the Lisp Lesser GNU Public License
;; (http://opensource.franz.com/preamble.html),
;; known as the LLGPL." > $1
